# Just a simple Ubuntu server install on a local VM, you want to customize it
# to your deploy
# See ../README.md for details
tooltracker:
  hosts:
    "10.1.0.2":
      ansible_user: root
      # Because we create VMs on demand
      ansible_host_key_checking: false
      tooltracker:
        mode: imap
        config:
          # These need to be defined here as they are used by the Apache config too
          listen: localhost # Only Apache needs to connect
          http-port: 8123 # Port of tooltracker, not the HTTP server
          http-prefix: "" # We have a separate subdomain
          # Mail configuration
          from: ".*@carallon.com"
          domain: "{{ inventory_hostname }}" # The email address "@..." part
          to: "robert.kovacsics+tooltracker" # The email address "...@" part
          dkim: carallon.com # The signed domain
          local-dkim: false
          # Mail fetching
          imap-host: outlook.office365.com:993
          imap-user: robert.kovacsics@carallon.com
          token-cmd: ["/var/lib/tooltracker/bin/pizauth", "show", "carallon"]
          mailbox: tooltracker
          idle-poll: "15m"
