# Just a simple Ubuntu server install on a local VM, you want to customize it
# to your deploy
# See ../README.md for details
tooltracker:
  hosts:
    "10.1.0.2":
      ansible_user: root
      # Because we create VMs on demand
      ansible_host_key_checking: false
      tooltracker:
        version: v1.0.0-beta.5
        install_path: /opt/tooltracker/bin
        listen: "{{ inventory_hostname }}"
        http_prefix: "tooltracker"
        http_port: 8123 # Port of tooltracker, not the HTTP server
        # Mail configuration
        smtp_port: 25
        to_user: tooltracker # The email address "...@" part
        domain: "{{ inventory_hostname }}" # The email address "@..." part
        from_re: ".*"
        db_path: tooltracker.db
        dkim: "tooltracker.office.carallon.com" # The signed domain
