---
- name: Install tooltracker
  hosts: tooltracker
  roles:
    - tooltracker
  tasks:
    # Install/configure pizauth ================================================
    - name: Install cargo
      ansible.builtin.apt:
        name: cargo
        state: present

    - name: Install pizauth
      ansible.builtin.command:
        argv:
          - "cargo"
          - "install"
          - "--git"
          - "https://github.com/ltratt/pizauth"
          - "--root"
          - "/var/lib/tooltracker"
        creates: "/var/lib/tooltracker/bin/pizauth"

    - name: Configure pizauth
      ansible.builtin.template:
        src: files/pizauth.conf.j2
        dest: /var/lib/tooltracker/pizauth.conf
      notify: ["Reload pizauth"]

    - name: Start pizauth
      ansible.builtin.template:
        src: files/pizauth.service.j2
        dest: /etc/systemd/system/pizauth.service
      notify: ["Reload pizauth"]

  handlers:
    - name: Reload pizauth
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: pizauth
        enabled: true
        state: reloaded
      notify: ["Restart tooltracker service"]
